# Generated by Django 5.1.3 on 2024-11-29 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urticket_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='event_images/')),
                ('date_time', models.DateTimeField()),
                ('title', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urticket_app.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='urticket_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Early Bird', 'Early Bird'), ('Regular', 'Regular'), ('VIP', 'VIP'), ('Gate Ticket', 'Gate Ticket'), ('Group of 3', 'Group of 3'), ('Group of 5', 'Group of 5')], max_length=50, null=True)),
                ('price', models.FloatField(help_text='Set the price for this ticket type', null=True)),
                ('qavailable', models.PositiveIntegerField(help_text='Number of tickets available for this type', verbose_name='Quantity Available')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urticket_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urticket_app.order')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urticket_app.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='urticket_app.ticket'),
        ),
    ]
