# Generated by Django 5.1.3 on 2024-11-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urticket_app', '0002_event_order_ticket_orderitem_order_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ticket',
        ),
    ]
